# vi: ft=dockerfile

FROM base/archlinux
RUN useradd -m -G wheel -s /bin/bash monkey
RUN pacman-db-upgrade
RUN pacman -Syyu --noconfirm && pacman --noconfirm -S python2-pip bower git
RUN pip2 install SPARQLWrapper
USER monkey
WORKDIR /code
#CMD python

